// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl7f-m1zCwfdBXN49M_Jl8sfmSryIogAE',
    appId: '1:571006113449:web:78903bbec2b1b0048d3bb8',
    messagingSenderId: '571006113449',
    projectId: 'fragram-1441b',
    authDomain: 'fragram-1441b.firebaseapp.com',
    storageBucket: 'fragram-1441b.firebasestorage.app',
    measurementId: 'G-Z21NPRT9QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuhzcYtM43qfQorSyX5rNkQEOr8ERZTTQ',
    appId: '1:571006113449:android:0f886190fe98b9ba8d3bb8',
    messagingSenderId: '571006113449',
    projectId: 'fragram-1441b',
    storageBucket: 'fragram-1441b.firebasestorage.app',
  );
}
